CHAT_MEMBER = 'Member'
CHAT_ADMIN = "Admin"

ROLES_CHOICES = [
        (CHAT_MEMBER, "Member"),
        (CHAT_ADMIN, "Admin"),
    ]

MESSAGE_STATUS_SEND = 'Отправлено'
MESSAGE_STATUS_DELIVERED = 'Доставлено'
MESSAGE_STATUS_READ = 'Прочитано'

MESSAGE_STATUS_CHOICES = [
    (MESSAGE_STATUS_SEND, MESSAGE_STATUS_SEND),
    (MESSAGE_STATUS_DELIVERED, MESSAGE_STATUS_DELIVERED),
    (MESSAGE_STATUS_READ, MESSAGE_STATUS_READ),
]

USER_HAS_BEEN_ADDED = 'Добавлен пользователь'
USER_HAS_BEEN_EXCLUDED = 'Пользователь исключён'
CHAT_CREATED = 'Чат создан'


MANAGE_MESSAGE_TYPE = [
    (USER_HAS_BEEN_ADDED, USER_HAS_BEEN_ADDED),
    (USER_HAS_BEEN_EXCLUDED, USER_HAS_BEEN_EXCLUDED),
    (CHAT_CREATED, CHAT_CREATED)
]
