# Generated by Django 5.0.2 on 2024-02-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "профиль пользователя",
                "verbose_name_plural": "профили пользователей",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="profile_photos/default.png",
                upload_to="profile_photos",
                verbose_name="фото профиля",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline")],
                default="offline",
                max_length=255,
                verbose_name="Статус",
            ),
        ),
    ]
