# Generated by Django 5.0.2 on 2024-02-08 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Отправлено", "Отправлено"),
                            ("Доставлено", "Доставлено"),
                            ("Прочитано", "Прочитано"),
                        ],
                        default="Отправлено",
                        max_length=255,
                    ),
                ),
                ("manage", models.BooleanField(default=False)),
                (
                    "manage_type",
                    models.CharField(
                        choices=[
                            ("Добавлен пользователь", "Добавлен пользователь"),
                            ("Пользователь исключён", "Пользователь исключён"),
                            ("Чат создан", "Чат создан"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.basechat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
