# Generated by Django 5.0.2 on 2024-02-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderedChat",
            fields=[],
            options={
                "ordering": ["-date_updated"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chats.basechat",),
        ),
        migrations.AlterModelOptions(
            name="basechat",
            options={"verbose_name": "чат", "verbose_name_plural": "чаты"},
        ),
        migrations.AlterModelOptions(
            name="channel",
            options={"verbose_name": "канал", "verbose_name_plural": "каналы"},
        ),
        migrations.AlterModelOptions(
            name="chatmember",
            options={
                "verbose_name": "участник чата",
                "verbose_name_plural": "участники чата",
            },
        ),
        migrations.AlterModelOptions(
            name="directchat",
            options={
                "verbose_name": "личный чат",
                "verbose_name_plural": "личные чаты",
            },
        ),
        migrations.AlterModelOptions(
            name="groupchat",
            options={
                "verbose_name": "групповой чат",
                "verbose_name_plural": "групповые чаты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "сообщение", "verbose_name_plural": "сообщения"},
        ),
    ]
