# Generated by Django 5.0.2 on 2024-02-16 11:48

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_orderedchat_alter_basechat_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmember",
            options={
                "verbose_name": "участник чата",
                "verbose_name_plural": "участники чатов",
            },
        ),
        migrations.AddField(
            model_name="basechat",
            name="uuid",
            field=models.CharField(
                default=uuid.UUID("2eb5d50f-4899-494f-b127-c14d7ba36e28"),
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="uuid",
            field=models.CharField(
                default=uuid.UUID("6e014e38-50de-454e-8203-f44db6e8711b"),
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="basechat",
            name="users",
            field=models.ManyToManyField(
                related_name="chats",
                through="chats.ChatMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
